"""add ai image columns

Revision ID: 1741b907d593
Revises: 0009_admin_dashboard
Create Date: 2026-08-02 19:28:39.622718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1741b907d593'
down_revision: Union[str, None] = '0009_admin_dashboard'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'recommended_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('budgets', 'spent_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('budgets', 'remaining_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('budgets', 'period',
               existing_type=postgresql.ENUM('weekly', 'monthly', 'yearly', name='budgetperiod'),
               nullable=False,
               existing_server_default=sa.text("'monthly'::budgetperiod"))
    op.alter_column('budgets', 'status',
               existing_type=postgresql.ENUM('safe', 'warning', 'exceeded', name='budgetstatus'),
               nullable=False,
               existing_server_default=sa.text("'safe'::budgetstatus"))
    op.alter_column('budgets', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('budgets', 'alert_threshold_percent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('80'))
    op.alter_column('budgets', 'color',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'#22B573'::character varying"))
    op.alter_column('budgets', 'auto_reset',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'is_read_by_user',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('chat_messages', 'is_read_by_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('expenses', sa.Column('ai_image_url', sa.Text(), nullable=True))
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'UZS'::character varying"))
    op.alter_column('expenses', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('expenses', 'recurrence_interval',
               existing_type=postgresql.ENUM('none', 'daily', 'weekly', 'monthly', 'yearly', name='recurrenceinterval'),
               nullable=False,
               existing_server_default=sa.text("'none'::recurrenceinterval"))
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('goals', sa.Column('image_url', sa.Text(), nullable=True))
    op.alter_column('goals', 'current_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('goals', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('incomes', 'currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'UZS'::character varying"))
    op.alter_column('incomes', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('incomes', 'recurrence_interval',
               existing_type=postgresql.ENUM('none', 'daily', 'weekly', 'monthly', 'yearly', name='recurrenceinterval'),
               nullable=False,
               existing_server_default=sa.text("'none'::recurrenceinterval"))
    op.alter_column('incomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('incomes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_queries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_queries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'language',
               existing_type=postgresql.ENUM('uz', 'en', 'ru', name='language'),
               nullable=False,
               existing_server_default=sa.text("'uz'::language"))
    op.alter_column('users', 'theme',
               existing_type=postgresql.ENUM('light', 'dark', name='theme'),
               nullable=False,
               existing_server_default=sa.text("'light'::theme"))
    op.alter_column('users', 'currency',
               existing_type=postgresql.ENUM('UZS', 'USD', 'EUR', name='currency'),
               nullable=False,
               existing_server_default=sa.text("'UZS'::currency"))
    op.alter_column('users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'currency',
               existing_type=postgresql.ENUM('UZS', 'USD', 'EUR', name='currency'),
               nullable=True,
               existing_server_default=sa.text("'UZS'::currency"))
    op.alter_column('users', 'theme',
               existing_type=postgresql.ENUM('light', 'dark', name='theme'),
               nullable=True,
               existing_server_default=sa.text("'light'::theme"))
    op.alter_column('users', 'language',
               existing_type=postgresql.ENUM('uz', 'en', 'ru', name='language'),
               nullable=True,
               existing_server_default=sa.text("'uz'::language"))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('market_queries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_queries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incomes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incomes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incomes', 'recurrence_interval',
               existing_type=postgresql.ENUM('none', 'daily', 'weekly', 'monthly', 'yearly', name='recurrenceinterval'),
               nullable=True,
               existing_server_default=sa.text("'none'::recurrenceinterval"))
    op.alter_column('incomes', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('incomes', 'currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'UZS'::character varying"))
    op.alter_column('goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('goals', 'current_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_column('goals', 'image_url')
    op.alter_column('expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'recurrence_interval',
               existing_type=postgresql.ENUM('none', 'daily', 'weekly', 'monthly', 'yearly', name='recurrenceinterval'),
               nullable=True,
               existing_server_default=sa.text("'none'::recurrenceinterval"))
    op.alter_column('expenses', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'UZS'::character varying"))
    op.drop_column('expenses', 'ai_image_url')
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'is_read_by_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('chat_messages', 'is_read_by_user',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('budgets', 'auto_reset',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('budgets', 'color',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'#22B573'::character varying"))
    op.alter_column('budgets', 'alert_threshold_percent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('80'))
    op.alter_column('budgets', 'progress_percent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('budgets', 'status',
               existing_type=postgresql.ENUM('safe', 'warning', 'exceeded', name='budgetstatus'),
               nullable=True,
               existing_server_default=sa.text("'safe'::budgetstatus"))
    op.alter_column('budgets', 'period',
               existing_type=postgresql.ENUM('weekly', 'monthly', 'yearly', name='budgetperiod'),
               nullable=True,
               existing_server_default=sa.text("'monthly'::budgetperiod"))
    op.alter_column('budgets', 'remaining_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('budgets', 'spent_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('budgets', 'recommended_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ai_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
